networks:
  jenkins:
    external: true

volumes:
  jenkins_home:
  jenkins-docker-certs:

services:
  docker:
    image: docker:dind
    container_name: docker-dind
    privileged: true
    networks:
      - jenkins
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins_home:/var/jenkins_home
    ports:
      - "2376:2376"
    environment:
      DOCKER_TLS_CERTDIR: /certs
    command: --storage-driver overlay2

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    depends_on:
      - docker
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      - jenkins

